### ISSUE TITLE
Create a README and license file

### ISSUE THREAD

**Issue by kelcecil** [jmccarty3/nodeSeppuku#1]
A README would be helpful for getting started. Someone will eventually inquire about the license, so you should pick that too.

**Comment by sstarcher** [comment]
Can we get an artful monolog of a node thinking to itself talking about it's last minutes and it's life decisions leading up to seppuku?

**Comment by kelcecil** [comment]
Ohhhhh! Agreed!

**Comment by kelcecil** [comment]
Here's a monologue for you. 

> "My life wasn't such a waste I'd decided. I'd served many exotic web browsers and processed many curious workloads. Perhaps my uptime wasn't what I had hoped for, but I had made the most of it. This, I thought to myself as my final daemons began to leave my memory, is all a node can really ask for. _**Halt**_."

**Comment by nyxcharon** [comment]
+1

**Comment by masneyb** [comment]
+1
